//! JavaScript Engine Integration for FabricOS
//!
//! Wraps V8 C++ FFI with FPU guard and provides safe Rust entry points.
//! All V8 calls go through `FpuGuard` to enable SSE2 at the FFI boundary.
//!
//! ## Usage
//! ```rust,ignore
//! js_engine::init();
//! let result = js_engine::eval("1 + 2");
//! js_engine::shutdown();
//! ```

#![allow(dead_code)]

use core::ffi::{c_void, c_int, c_char};
use core::sync::atomic::{AtomicBool, Ordering};
use crate::v8_platform::fpu_guard::FpuGuard;

// ============================================================================
// V8 C++ FFI Declarations
// ============================================================================
//
// These symbols are provided by libv8.a + platform_fabric.cc.
// They wrap the V8 C++ API in a flat C interface for Rust consumption.

extern "C" {
    /// Initialize V8 platform (thread pool, ICU, etc.)
    /// Must be called once before any other V8 function.
    /// `thread_pool_size`: number of background worker threads (0 = default)
    fn fabricos_v8_initialize(thread_pool_size: c_int) -> c_int;

    /// Create a new V8 Isolate (independent JS execution context).
    /// `snapshot_data`: pointer to embedded startup snapshot blob
    /// `snapshot_len`: length of snapshot data in bytes
    /// Returns opaque isolate handle, or null on failure.
    fn fabricos_v8_create_isolate(
        snapshot_data: *const u8,
        snapshot_len: usize,
    ) -> *mut c_void;

    /// Execute a JavaScript string in the given isolate.
    /// `isolate`: handle from fabricos_v8_create_isolate
    /// `script`: UTF-8 script source (not null-terminated)
    /// `script_len`: length of script in bytes
    /// `filename`: null-terminated filename for error messages
    /// Returns: 0 on success, negative on error
    fn fabricos_v8_run_script(
        isolate: *mut c_void,
        script: *const u8,
        script_len: usize,
        filename: *const c_char,
    ) -> c_int;

    /// Execute JS and return an integer result.
    /// For scripts that evaluate to a number (e.g., "1+2" -> 3).
    /// `out_value`: pointer to write the integer result
    /// Returns: 0 on success, negative on error
    fn fabricos_v8_eval_int(
        isolate: *mut c_void,
        script: *const u8,
        script_len: usize,
        out_value: *mut i64,
    ) -> c_int;

    /// Trigger garbage collection in the isolate.
    fn fabricos_v8_gc(isolate: *mut c_void);

    /// Destroy a V8 Isolate, freeing all associated memory.
    fn fabricos_v8_dispose_isolate(isolate: *mut c_void);

    /// Shut down V8 platform. No V8 calls allowed after this.
    fn fabricos_v8_shutdown();

    /// Get V8 version string (null-terminated).
    fn fabricos_v8_version() -> *const c_char;

    /// Get V8 heap statistics for an isolate.
    /// `out_used`: bytes currently used
    /// `out_total`: bytes in heap (committed)
    /// `out_limit`: heap size limit
    fn fabricos_v8_heap_stats(
        isolate: *mut c_void,
        out_used: *mut usize,
        out_total: *mut usize,
        out_limit: *mut usize,
    );
}

// ============================================================================
// V8 Snapshot (embedded at build time)
// ============================================================================

/// Embedded V8 startup snapshot blob.
///
/// Generated by `mksnapshot` on the host with identical V8 configuration.
/// Contains pre-compiled builtins for fast startup. When no snapshot is
/// available yet (pre-L13.7), this is an empty slice and V8 starts from
/// scratch (slower but functional in jitless mode).
#[cfg(feature = "v8-snapshot")]
static V8_SNAPSHOT: &[u8] = include_bytes!("../../build/v8/snapshot_blob.bin");

#[cfg(not(feature = "v8-snapshot"))]
static V8_SNAPSHOT: &[u8] = &[];

// ============================================================================
// Engine State
// ============================================================================

static V8_INITIALIZED: AtomicBool = AtomicBool::new(false);

/// Errors from the JS engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JsError {
    /// V8 platform initialization failed
    InitFailed,
    /// V8 already initialized
    AlreadyInitialized,
    /// V8 not initialized
    NotInitialized,
    /// Isolate creation failed (OOM or snapshot mismatch)
    IsolateCreationFailed,
    /// Script execution error (syntax or runtime)
    ScriptError,
    /// Null pointer from FFI
    NullPointer,
}

// ============================================================================
// Public API — All entry points are FPU-guarded
// ============================================================================

/// Initialize V8 engine.
///
/// Sets up the V8 platform with the specified number of worker threads.
/// Must be called once before creating isolates.
pub fn init() -> Result<(), JsError> {
    init_with_threads(4)
}

/// Initialize V8 engine with custom thread pool size.
pub fn init_with_threads(thread_pool_size: u32) -> Result<(), JsError> {
    if V8_INITIALIZED.load(Ordering::Acquire) {
        return Err(JsError::AlreadyInitialized);
    }

    let _guard = FpuGuard::new();
    let result = unsafe { fabricos_v8_initialize(thread_pool_size as c_int) };

    if result != 0 {
        return Err(JsError::InitFailed);
    }

    V8_INITIALIZED.store(true, Ordering::Release);
    Ok(())
}

/// Opaque handle to a V8 Isolate.
///
/// Each isolate is an independent JavaScript execution environment with its
/// own heap. Isolates are single-threaded — only one thread may enter at a time.
pub struct JsIsolate {
    handle: *mut c_void,
}

// Isolates can be sent between threads (V8 supports this with proper locking)
unsafe impl Send for JsIsolate {}

impl JsIsolate {
    /// Create a new isolate with the embedded startup snapshot.
    pub fn new() -> Result<Self, JsError> {
        if !V8_INITIALIZED.load(Ordering::Acquire) {
            return Err(JsError::NotInitialized);
        }

        let _guard = FpuGuard::new();
        let (data, len) = if V8_SNAPSHOT.is_empty() {
            (core::ptr::null(), 0)
        } else {
            (V8_SNAPSHOT.as_ptr(), V8_SNAPSHOT.len())
        };

        let handle = unsafe { fabricos_v8_create_isolate(data, len) };
        if handle.is_null() {
            return Err(JsError::IsolateCreationFailed);
        }

        Ok(Self { handle })
    }

    /// Execute a JavaScript script.
    ///
    /// `script`: UTF-8 JavaScript source code
    /// `filename`: source filename for error messages (shown in stack traces)
    pub fn exec(&self, script: &str, filename: &[u8]) -> Result<(), JsError> {
        let _guard = FpuGuard::new();
        let result = unsafe {
            fabricos_v8_run_script(
                self.handle,
                script.as_ptr(),
                script.len(),
                filename.as_ptr() as *const c_char,
            )
        };

        if result < 0 {
            Err(JsError::ScriptError)
        } else {
            Ok(())
        }
    }

    /// Evaluate a JavaScript expression and return its integer value.
    ///
    /// For expressions like "1 + 2" that evaluate to a number.
    pub fn eval_int(&self, script: &str) -> Result<i64, JsError> {
        let _guard = FpuGuard::new();
        let mut value: i64 = 0;
        let result = unsafe {
            fabricos_v8_eval_int(
                self.handle,
                script.as_ptr(),
                script.len(),
                &mut value as *mut i64,
            )
        };

        if result < 0 {
            Err(JsError::ScriptError)
        } else {
            Ok(value)
        }
    }

    /// Trigger garbage collection.
    pub fn gc(&self) {
        let _guard = FpuGuard::new();
        unsafe { fabricos_v8_gc(self.handle); }
    }

    /// Get heap usage statistics.
    ///
    /// Returns (used_bytes, total_bytes, limit_bytes).
    pub fn heap_stats(&self) -> (usize, usize, usize) {
        let _guard = FpuGuard::new();
        let mut used = 0usize;
        let mut total = 0usize;
        let mut limit = 0usize;
        unsafe {
            fabricos_v8_heap_stats(
                self.handle,
                &mut used as *mut usize,
                &mut total as *mut usize,
                &mut limit as *mut usize,
            );
        }
        (used, total, limit)
    }
}

impl Drop for JsIsolate {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            let _guard = FpuGuard::new();
            unsafe { fabricos_v8_dispose_isolate(self.handle); }
            self.handle = core::ptr::null_mut();
        }
    }
}

/// Shut down V8 engine.
///
/// All isolates must be dropped before calling this.
/// No V8 calls are allowed after shutdown.
pub fn shutdown() {
    if !V8_INITIALIZED.load(Ordering::Acquire) {
        return;
    }

    let _guard = FpuGuard::new();
    unsafe { fabricos_v8_shutdown(); }
    V8_INITIALIZED.store(false, Ordering::Release);
}

/// Check if V8 is initialized.
pub fn is_initialized() -> bool {
    V8_INITIALIZED.load(Ordering::Acquire)
}

// ============================================================================
// Smoke Test — validates L13.7 link test readiness
// ============================================================================

/// Run the V8 smoke test: initialize, create isolate, eval "1+2", verify result.
///
/// This is the L13.7 link test entry point. Call after kernel boot with V8 linked.
pub fn smoke_test() -> Result<(), JsError> {
    init()?;

    let isolate = JsIsolate::new()?;
    let result = isolate.eval_int("1 + 2")?;

    if result != 3 {
        return Err(JsError::ScriptError);
    }

    // Verify GC doesn't crash
    isolate.gc();

    // Check heap stats are non-zero
    let (used, total, _limit) = isolate.heap_stats();
    if used == 0 || total == 0 {
        return Err(JsError::ScriptError);
    }

    drop(isolate);
    shutdown();

    Ok(())
}
